export const TestProfiles = [
  {
    id: '1',
    name: 'Emma',
    age: 25,
    images: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400&h=600&fit=crop'
    ],
    bio: 'Passionnée de photographie et de voyages 📸✈️...',
    location: 'Paris',
    occupation: 'Photographe',
    interests: ['Photographie', 'Voyage', 'Art', 'Cuisine'],
    distance: 2,
    personalOpinion: 'Je crois au bonheur simple et aux petites aventures.',
    educationLevel: 'Master',
    socialActivityLevel: 'Élevée',
    sportActivity: 'Modérée',
    religion: 'Aucune',
    childrenStatus: 'Aucun',
    zodiacSign: 'Lion',
    hairColor: 'Châtain',
    skinColor: 'Clair',
    eyeColor: 'Bleus',
    birthCity: 'Lyon',
    currentCity: 'Paris',
    job: 'Photographe freelance',
  },
  {
    id: '2',
    name: 'Sophie',
    age: 28,
    images: [
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&h=600&fit=crop'
    ],
    bio: 'Designer UX/UI qui adore créer des expériences uniques...',
    location: 'Lyon',
    occupation: 'UX Designer',
    interests: ['Design', 'Tech', 'Fitness', 'Lecture'],
    distance: 5,
    personalOpinion: 'La créativité doit guider toutes mes actions.',
    educationLevel: 'Licence',
    socialActivityLevel: 'Modérée',
    sportActivity: 'Élevée',
    religion: 'Agnostique',
    childrenStatus: 'Aucun',
    zodiacSign: 'Balance',
    hairColor: 'Blond',
    skinColor: 'Clair',
    eyeColor: 'Verts',
    birthCity: 'Marseille',
    currentCity: 'Lyon',
    job: 'UX Designer chez TechCorp',
  },
];
