name: Pre-commit Checks

on:
  push:
    branches:
      - '*'  # Run on all branches
  workflow_dispatch:  # Allow manual triggering

jobs:
  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for pre-commit to work properly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download Go modules
        run: |
          for dir in api/*/; do
            if [ -f "$dir/go.mod" ]; then
              echo "Downloading modules for $dir"
              (cd "$dir" && go mod download) || exit 1
            fi
          done

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: frontend

      - name: Install Python dependencies for services
        run: |
          # Install pre-commit and linting tools
          pip install pre-commit black flake8 isort

          # Install dependencies for Python services (needed for imports)
          for dir in api/*/; do
            if [ -f "$dir/requirements.txt" ]; then
              echo "Installing dependencies for $dir"
              pip install -r "$dir/requirements.txt" || exit 1
            fi
          done

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
